// src/components/FeedbackCell.tsx
import type { CSSProperties } from 'react'

import type { Direction, MatchResult } from '../game/types'
import { t, type Locale } from '../i18n'

export interface FeedbackCellProps {
  readonly label: string
  readonly value: string
  readonly result: MatchResult
  readonly direction?: Direction | null
  readonly cellIndex: number
  readonly locale: Locale
}

export function FeedbackCell({
  label,
  value,
  result,
  direction,
  cellIndex,
  locale,
}: FeedbackCellProps) {
  const statusIcon = result === 'exact' ? '✓' : result === 'partial' ? '◐' : '×'
  const statusText = t(locale, `feedback.${result}`)
  const directionIcon = direction === 'up' ? '↑' : '↓'
  const directionText =
    direction === 'up' ? t(locale, 'feedback.higher') : t(locale, 'feedback.lower')
  const separator = locale === 'zh-CN' ? '，' : ', '
  const labelSeparator = locale === 'zh-CN' ? '：' : ': '
  const accessibleLabel = [
    `${label}${labelSeparator}${value}`,
    statusText,
    ...(direction ? [directionText] : []),
  ].join(separator)
  const style = { '--cell-index': cellIndex } as CSSProperties

  return (
    <div
      className={`feedback-cell feedback-cell--${result}`}
      style={style}
      aria-label={accessibleLabel}
    >
      <span className="feedback-cell__mobile-label" aria-hidden="true">
        {label}
      </span>
      <span className="feedback-cell__status" title={statusText} aria-hidden="true">
        {statusIcon}
      </span>
      <span
        className={`feedback-cell__readout${
          direction ? ' feedback-cell__readout--directional' : ''
        }`}
      >
        <span className="feedback-cell__value">{value}</span>
        {direction ? (
          <span className="feedback-cell__direction" aria-hidden="true">
            {directionIcon}
          </span>
        ) : null}
      </span>
    </div>
  )
}

export default FeedbackCell

// src/components/FeedbackCell.vue
<script setup lang="ts">
import { computed } from 'vue'

import type { Direction, MatchResult } from '../game/types'
import { t, type Locale } from '../i18n'

const props = defineProps<{
  label: string
  value: string
  result: MatchResult
  direction?: Direction | null
  cellIndex: number
  locale: Locale
}>()

const statusIcon = computed(() => {
  if (props.result === 'exact') return '✓'
  if (props.result === 'partial') return '◐'
  return '×'
})

const statusText = computed(() => t(props.locale, `feedback.${props.result}`))
const directionIcon = computed(() => (props.direction === 'up' ? '↑' : '↓'))
const directionText = computed(() =>
  props.direction === 'up' ? t(props.locale, 'feedback.higher') : t(props.locale, 'feedback.lower'),
)
const accessibleLabel = computed(() => {
  const separator = props.locale === 'zh-CN' ? '，' : ', '
  const labelSeparator = props.locale === 'zh-CN' ? '：' : ': '
  return [
    `${props.label}${labelSeparator}${props.value}`,
    statusText.value,
    ...(props.direction ? [directionText.value] : []),
  ].join(separator)
})
</script>

<template>
  <div
    class="feedback-cell"
    :class="`feedback-cell--${result}`"
    :style="{ '--cell-index': cellIndex }"
    :aria-label="accessibleLabel"
  >
    <span class="feedback-cell__mobile-label" aria-hidden="true">{{ label }}</span>
    <span class="feedback-cell__status" :title="statusText" aria-hidden="true">
      {{ statusIcon }}
    </span>
    <span class="feedback-cell__value">{{ value }}</span>
    <span v-if="direction" class="feedback-cell__direction" aria-hidden="true">
      {{ directionIcon }}
    </span>
  </div>
</template>
