// src/App.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { BarChart3, BookOpen, CircleHelp, Languages, ListTree } from 'lucide-react'

import ClueGlossaryDialog from './components/ClueGlossaryDialog'
import GuessRow from './components/GuessRow'
import HelpDialog from './components/HelpDialog'
import JokerCombobox from './components/JokerCombobox'
import JokerCollectionDialog from './components/JokerCollectionDialog'
import ResultBanner from './components/ResultBanner'
import StatsDialog from './components/StatsDialog'
import { JOKER_DATA_META, jokers } from './data'
import type { Joker } from './data/types'
import {
  compareJokers,
  createDailyGame,
  createPracticeGame,
  avoidImmediatePracticeRepeat,
  formatShareResult,
  GAME_CLUE_MODEL_VERSION,
  GAME_STORAGE_FALLBACK_CLASSIFICATION_VERSIONS,
  gameStorageKey,
  getBeijingDateKey,
  markCollectionUsed,
  restoreStoredGame,
  serializeGameState,
  submitGuess,
  type GameMode,
  type GameState,
  type GuessComparison,
} from './game'
import {
  LOCALE_STORAGE_KEY,
  resolveLocale,
  serializeLocalePreference,
  t,
  type Locale,
  type MessageKey,
} from './i18n'
import {
  STATS_STORAGE_KEY,
  parseStats,
  recordCompletedDailyGame,
  type PlayerStats,
} from './state/stats'

const PROJECT_LINKS = {
  source: 'https://github.com/x6ncraft/balatrue',
  x: 'https://x.com/x6ncraft',
  bilibili: 'https://space.bilibili.com/2056733',
  balatro: 'https://www.playbalatro.com/',
  wiki: 'https://balatrowiki.org/',
} as const

const bootTime = new Date()
const today = getBeijingDateKey(bootTime)
const initialDailyGame = createDailyGame(jokers, bootTime)
const dailyAnswer = initialDailyGame.answerId
const dataKey = `${JOKER_DATA_META.gameVersion}:c${JOKER_DATA_META.classificationVersion}:g${GAME_CLUE_MODEL_VERSION}`
const dailyStorageKey = gameStorageKey(
  JOKER_DATA_META.gameVersion,
  JOKER_DATA_META.classificationVersion,
  'daily',
  today,
  GAME_CLUE_MODEL_VERSION,
)
const practiceStorageKey = gameStorageKey(
  JOKER_DATA_META.gameVersion,
  JOKER_DATA_META.classificationVersion,
  'practice',
  undefined,
  GAME_CLUE_MODEL_VERSION,
)
const previousClassificationVersions = GAME_STORAGE_FALLBACK_CLASSIFICATION_VERSIONS.filter(
  (version) => version < JOKER_DATA_META.classificationVersion,
)
const previousClueModel = { classificationVersion: 8, clueModelVersion: 2 } as const
const previousDailyStorageKeys = [
  gameStorageKey(
    JOKER_DATA_META.gameVersion,
    JOKER_DATA_META.classificationVersion,
    'daily',
    today,
  ),
  gameStorageKey(
    JOKER_DATA_META.gameVersion,
    previousClueModel.classificationVersion,
    'daily',
    today,
    previousClueModel.clueModelVersion,
  ),
  ...previousClassificationVersions.map((version) =>
    gameStorageKey(JOKER_DATA_META.gameVersion, version, 'daily', today),
  ),
]
const previousPracticeStorageKeys = [
  gameStorageKey(JOKER_DATA_META.gameVersion, JOKER_DATA_META.classificationVersion, 'practice'),
  gameStorageKey(
    JOKER_DATA_META.gameVersion,
    previousClueModel.classificationVersion,
    'practice',
    undefined,
    previousClueModel.clueModelVersion,
  ),
  ...previousClassificationVersions.map((version) =>
    gameStorageKey(JOKER_DATA_META.gameVersion, version, 'practice'),
  ),
]
const practiceBagKey = `balatrue:practice-bag:${dataKey}`
const previousPracticeBagKeys = [
  `balatrue:practice-bag:${JOKER_DATA_META.gameVersion}:c${JOKER_DATA_META.classificationVersion}`,
  `balatrue:practice-bag:${JOKER_DATA_META.gameVersion}:c${previousClueModel.classificationVersion}:g${previousClueModel.clueModelVersion}`,
  ...previousClassificationVersions.map(
    (version) => `balatrue:practice-bag:${JOKER_DATA_META.gameVersion}:c${version}`,
  ),
]
const validJokerIds = new Set(jokers.map((joker) => joker.id))
const jokersById = new Map(jokers.map((joker) => [joker.id, joker]))

function safeStorageGet(key: string): string | null {
  try {
    return localStorage.getItem(key)
  } catch {
    return null
  }
}

function safeStorageSet(key: string, value: string): boolean {
  try {
    localStorage.setItem(key, value)
    return true
  } catch {
    return false
  }
}

function refreshFallbackGame(storedState: GameState): GameState | null {
  const storedAnswer = jokersById.get(storedState.answerId)
  if (!storedAnswer) return null

  let refreshed: GameState = {
    ...storedState,
    status: 'playing',
    guesses: [],
  }
  try {
    for (const storedGuess of storedState.guesses) {
      const guessedJoker = jokersById.get(storedGuess.guessId)
      if (!guessedJoker) return null
      refreshed = submitGuess(refreshed, guessedJoker, storedAnswer)
    }
  } catch {
    return null
  }
  return refreshed.status === storedState.status ? refreshed : null
}

function restoredGame(
  key: string,
  fallbackKeys: readonly string[],
  mode: GameMode,
  answerId?: string,
): GameState | null {
  if (mode === 'daily' && !answerId) return null
  return restoreStoredGame({
    currentKey: key,
    fallbackKeys,
    context:
      mode === 'daily'
        ? { mode, puzzleKey: today, answerId: answerId as string }
        : { mode: 'practice' },
    validJokerIds,
    read: safeStorageGet,
    write: safeStorageSet,
    refreshFallback: refreshFallbackGame,
  })
}

function shuffledIds(): string[] {
  const result = jokers.map((joker) => joker.id)
  for (let index = result.length - 1; index > 0; index -= 1) {
    const random = new Uint32Array(1)
    crypto.getRandomValues(random)
    const swapIndex = (random[0] ?? 0) % (index + 1)
    const current = result[index]
    const swap = result[swapIndex]
    if (current && swap) {
      result[index] = swap
      result[swapIndex] = current
    }
  }
  return result
}

function nextPracticeGame(avoidId?: string): GameState {
  let bag: string[] | null = null
  for (const key of [practiceBagKey, ...previousPracticeBagKeys]) {
    const raw = safeStorageGet(key)
    if (raw === null) continue
    try {
      const stored: unknown = JSON.parse(raw)
      if (Array.isArray(stored)) {
        bag = [
          ...new Set(
            stored.filter((id): id is string => typeof id === 'string' && validJokerIds.has(id)),
          ),
        ]
        break
      }
    } catch {
      // Try an older bag before starting a fresh cycle.
    }
  }
  if (!bag?.length) bag = shuffledIds()
  bag = avoidImmediatePracticeRepeat(bag, avoidId)
  if (bag[0] === avoidId) bag = avoidImmediatePracticeRepeat(shuffledIds(), avoidId)

  const answerId = bag.shift()
  if (!answerId) throw new Error('No Joker is available for practice mode')
  const sorted = [...jokers].sort((left, right) => left.number - right.number)
  const answerIndex = sorted.findIndex((joker) => joker.id === answerId)
  const randomValue = (Math.max(0, answerIndex) + 0.5) / sorted.length
  safeStorageSet(practiceBagKey, JSON.stringify(bag))

  return createPracticeGame(jokers, () => randomValue, {
    puzzleKey: `practice:${Date.now().toString(36)}`,
  })
}

function sameVisibleFeedback(left: GuessComparison, right: GuessComparison): boolean {
  return (
    left.rarity.result === right.rarity.result &&
    left.rarity.direction === right.rarity.direction &&
    left.acquisition.result === right.acquisition.result &&
    left.acquisition.direction === right.acquisition.direction &&
    left.effects.result === right.effects.result &&
    left.timings.result === right.timings.result &&
    left.dependencies.result === right.dependencies.result
  )
}

export default function App() {
  const [locale, setLocale] = useState<Locale>(() =>
    resolveLocale({
      stored: safeStorageGet(LOCALE_STORAGE_KEY),
      preferredLanguages: navigator.languages,
    }),
  )
  const [mode, setModeState] = useState<GameMode>('daily')
  const [dailyState, setDailyState] = useState<GameState>(
    () =>
      restoredGame(dailyStorageKey, previousDailyStorageKeys, 'daily', dailyAnswer) ??
      initialDailyGame,
  )
  const [practiceState, setPracticeState] = useState<GameState | null>(() =>
    restoredGame(practiceStorageKey, previousPracticeStorageKeys, 'practice'),
  )
  const [helpOpen, setHelpOpen] = useState(false)
  const [statsOpen, setStatsOpen] = useState(false)
  const [glossaryOpen, setGlossaryOpen] = useState(false)
  const [collectionOpen, setCollectionOpen] = useState(false)
  const [notice, setNotice] = useState<MessageKey | null>(null)
  const [copied, setCopied] = useState(false)
  const [resetToken, setResetToken] = useState(0)
  const initialStats = useMemo(() => parseStats(safeStorageGet(STATS_STORAGE_KEY)), [])
  const [stats, setStats] = useState<PlayerStats>(initialStats)
  const statsRef = useRef(initialStats)
  const pendingReveal = useRef(false)
  const copyTimer = useRef<number | null>(null)

  const state = mode === 'daily' || practiceState === null ? dailyState : practiceState
  const answer = useMemo(() => {
    const found = jokersById.get(state.answerId)
    if (!found) throw new Error(`Missing answer ${state.answerId}`)
    return found
  }, [state.answerId])
  const guessedIds = useMemo(() => state.guesses.map((guess) => guess.guessId), [state.guesses])
  const guessRows = useMemo(
    () =>
      state.guesses.flatMap((comparison) => {
        const joker = jokersById.get(comparison.guessId)
        return joker ? [{ joker, comparison }] : []
      }),
    [state.guesses],
  )
  const remainingAttempts = state.maxAttempts - state.guesses.length
  const requiresCollectionConfirmation =
    mode === 'daily' && state.status === 'playing' && !state.usedCollection

  const possibleCount = useMemo(() => {
    if (state.guesses.length === 0) return jokers.length
    if (state.status === 'won') return 1
    const guessed = new Set(guessedIds)

    return jokers.filter((candidate) => {
      if (guessed.has(candidate.id)) return false
      return state.guesses.every((record) => {
        const guessedJoker = jokersById.get(record.guessId)
        return guessedJoker
          ? sameVisibleFeedback(compareJokers(guessedJoker, candidate), record)
          : false
      })
    }).length
  }, [guessedIds, state.guesses, state.status])

  const saveState = useCallback((next: GameState) => {
    const key = next.mode === 'daily' ? dailyStorageKey : practiceStorageKey
    if (!safeStorageSet(key, serializeGameState(next))) {
      setNotice('error.storageUnavailable')
    }
  }, [])

  const finishDaily = useCallback((next: GameState) => {
    if (next.mode !== 'daily' || next.status === 'playing') return
    const updated = recordCompletedDailyGame(statsRef.current, next)
    if (updated === statsRef.current) return
    statsRef.current = updated
    setStats(updated)
    if (!safeStorageSet(STATS_STORAGE_KEY, JSON.stringify(updated))) {
      setNotice('error.storageUnavailable')
    }
  }, [])

  useEffect(() => {
    document.documentElement.lang = locale
    document.title = locale === 'zh-CN' ? 'Balatrue · 猜丑牌' : 'Balatrue · Daily Joker Puzzle'
    safeStorageSet(LOCALE_STORAGE_KEY, serializeLocalePreference(locale))
  }, [locale])

  useEffect(() => {
    finishDaily(dailyState)
  }, [dailyState, finishDaily])

  useEffect(() => {
    if (!pendingReveal.current) return
    pendingReveal.current = false
    const frame = window.requestAnimationFrame(() => {
      const target = document.querySelector<HTMLElement>(
        state.status === 'playing' ? '.guess-row:last-child' : '.result-banner',
      )
      if (!target) return
      const bounds = target.getBoundingClientRect()
      if (bounds.top >= 0 && bounds.bottom <= window.innerHeight) return
      const isNarrowScreen = window.matchMedia('(max-width: 760px)').matches
      target.scrollIntoView({
        block: isNarrowScreen ? 'center' : 'nearest',
        behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth',
      })
    })
    return () => window.cancelAnimationFrame(frame)
  }, [state.guesses.length, state.status])

  useEffect(
    () => () => {
      if (copyTimer.current !== null) window.clearTimeout(copyTimer.current)
    },
    [],
  )

  function submit(joker: Joker): void {
    setNotice(null)
    try {
      const next = submitGuess(state, joker, answer)
      if (mode === 'daily') setDailyState(next)
      else setPracticeState(next)
      saveState(next)
      pendingReveal.current = true
    } catch (error) {
      setNotice(
        error instanceof Error && error.message.includes('already')
          ? 'error.duplicateGuess'
          : 'error.invalidGuess',
      )
    }
  }

  function selectMode(next: GameMode): void {
    if (mode === next) return
    setNotice(null)
    if (next === 'practice' && !practiceState) {
      const practice = nextPracticeGame()
      setPracticeState(practice)
      saveState(practice)
    }
    setModeState(next)
    setCopied(false)
    setResetToken((current) => current + 1)
  }

  function startNext(): void {
    const practice = nextPracticeGame(state.mode === 'practice' ? state.answerId : undefined)
    setNotice(null)
    setPracticeState(practice)
    setModeState('practice')
    saveState(practice)
    setCopied(false)
    setResetToken((current) => current + 1)
  }

  function confirmCollection(): void {
    if (mode !== 'daily') return
    const next = markCollectionUsed(dailyState)
    if (next === dailyState) return
    setDailyState(next)
    setNotice('collection.assistedNotice')
    saveState(next)
  }

  async function copyResult(): Promise<void> {
    const result = formatShareResult(state, {
      title: 'Balatrue',
      url: window.location.origin,
    })
    let didCopy = false
    try {
      await navigator.clipboard.writeText(result)
      didCopy = true
    } catch {
      const textarea = document.createElement('textarea')
      textarea.value = result
      textarea.style.position = 'fixed'
      textarea.style.opacity = '0'
      document.body.append(textarea)
      textarea.select()
      didCopy = document.execCommand('copy')
      textarea.remove()
    }
    if (!didCopy) {
      setNotice('error.generic')
      return
    }
    setCopied(true)
    if (copyTimer.current !== null) window.clearTimeout(copyTimer.current)
    copyTimer.current = window.setTimeout(() => setCopied(false), 1800)
  }

  const visibleNotice = notice ? t(locale, notice) : ''

  return (
    <main className="app-shell">
      <header className="topbar">
        <div className="brand" aria-label="Balatrue 猜丑牌">
          <p className="brand__name">
            BALA<span>TRUE</span>
          </p>
          <p className="brand__zh">猜丑牌</p>
        </div>
        <nav className="top-actions" aria-label={locale === 'zh-CN' ? '页面工具' : 'Page tools'}>
          <button
            className="collection-button"
            type="button"
            aria-label={t(locale, 'a11y.openCollection')}
            onClick={() => setCollectionOpen(true)}
          >
            <BookOpen size={18} aria-hidden="true" />
            <span>{t(locale, 'nav.collection')}</span>
          </button>
          <button
            className="icon-button"
            type="button"
            aria-label={t(locale, 'stats.title')}
            onClick={() => setStatsOpen(true)}
          >
            <BarChart3 size={19} aria-hidden="true" />
          </button>
          <button
            className="icon-button"
            type="button"
            aria-label={t(locale, 'a11y.openHelp')}
            onClick={() => setHelpOpen(true)}
          >
            <CircleHelp size={19} aria-hidden="true" />
          </button>
          <button
            className="language-button"
            type="button"
            aria-label={t(locale, 'a11y.openLanguageMenu')}
            onClick={() => setLocale((current) => (current === 'zh-CN' ? 'en' : 'zh-CN'))}
          >
            <Languages size={18} aria-hidden="true" />
            <span>{locale === 'zh-CN' ? 'EN' : '中文'}</span>
          </button>
        </nav>
      </header>

      <section className="game-card" aria-labelledby="puzzle-title">
        <header className="game-card__head">
          <div className="game-heading-row">
            <div className="mode-switch" aria-label={locale === 'zh-CN' ? '游戏模式' : 'Game mode'}>
              <button
                type="button"
                aria-pressed={mode === 'daily'}
                onClick={() => selectMode('daily')}
              >
                {t(locale, 'nav.daily')}
              </button>
              <button
                type="button"
                aria-pressed={mode === 'practice'}
                onClick={() => selectMode('practice')}
              >
                {t(locale, 'nav.endless')}
              </button>
            </div>
            <div>
              <h1 id="puzzle-title" className="sr-only">
                {mode === 'daily' ? t(locale, 'brand.tagline') : t(locale, 'game.endlessTitle')}
              </h1>
              <p className="puzzle-rule">{t(locale, 'game.instructions')}</p>
            </div>
          </div>

          <JokerCombobox
            key={resetToken}
            jokers={jokers}
            locale={locale}
            guessedIds={guessedIds}
            disabled={state.status !== 'playing'}
            onSubmit={submit}
            onInvalid={() => setNotice('error.invalidGuess')}
          />

          <div className="game-meta">
            <div className="game-meta__right">
              <button className="glossary-link" type="button" onClick={() => setGlossaryOpen(true)}>
                <ListTree size={15} aria-hidden="true" />
                {t(locale, 'action.openGlossary')}
              </button>
              {state.mode === 'daily' && state.usedCollection ? (
                <span className="assisted-badge">
                  <BookOpen size={14} aria-hidden="true" />
                  {t(locale, 'game.assisted')}
                </span>
              ) : null}
              {state.status === 'playing' ? (
                <span className="game-meta__count">
                  {state.guesses.length === 0 ? (
                    t(locale, 'game.startingAttempts', { count: state.maxAttempts })
                  ) : (
                    <>
                      {t(locale, 'game.remaining', { count: remainingAttempts })} ·{' '}
                      {locale === 'zh-CN'
                        ? `约 ${possibleCount} 张仍符合线索`
                        : `About ${possibleCount} still fit`}
                    </>
                  )}
                </span>
              ) : null}
            </div>
          </div>
          {visibleNotice ? (
            <div className="notice" role="status">
              {visibleNotice}
            </div>
          ) : null}
        </header>

        <div className="guess-area">
          {state.status !== 'playing' ? (
            <ResultBanner
              state={state}
              answer={answer}
              locale={locale}
              copied={copied}
              onShare={() => void copyResult()}
              onNext={startNext}
            />
          ) : null}

          {guessRows.length === 0 ? (
            <div className="empty-board">
              <div>
                <span className="empty-board__mark" aria-hidden="true">
                  ?
                </span>
                <p>{t(locale, 'state.empty')}</p>
              </div>
            </div>
          ) : (
            <section className="guess-table" aria-label={t(locale, 'a11y.guessHistory')}>
              <div className="guess-header" aria-hidden="true">
                <span>{t(locale, 'clue.joker')}</span>
                <span>{t(locale, 'clue.rarity')}</span>
                <span>{t(locale, 'clue.price')}</span>
                <span>{t(locale, 'clue.effect')}</span>
                <span>{t(locale, 'clue.timing')}</span>
                <span>{t(locale, 'clue.dependency')}</span>
              </div>
              {guessRows.map((row) => (
                <GuessRow
                  key={row.joker.id}
                  joker={row.joker}
                  comparison={row.comparison}
                  locale={locale}
                />
              ))}
            </section>
          )}
        </div>
      </section>

      <footer className="site-footer">
        <div className="site-footer__about">
          <p className="site-footer__brand">
            {t(locale, 'footer.madeByPrefix')}
            <a href={PROJECT_LINKS.x} target="_blank" rel="noopener noreferrer">
              @x6ncraft
            </a>
            {t(locale, 'footer.madeBySuffix')}
          </p>
          <p>{t(locale, 'brand.disclaimer')}</p>
          <p>
            {JOKER_DATA_META.gameVersion} · 150 Jokers · {t(locale, 'footer.localProgress')}
          </p>
        </div>
        <nav className="site-footer__links" aria-label={t(locale, 'footer.links')}>
          <span className="site-footer__link-group">
            <a href={PROJECT_LINKS.source} target="_blank" rel="noopener noreferrer">
              {t(locale, 'footer.source')}
            </a>
            <a href={PROJECT_LINKS.x} target="_blank" rel="noopener noreferrer">
              X
            </a>
            <a href={PROJECT_LINKS.bilibili} target="_blank" rel="noopener noreferrer">
              {t(locale, 'footer.bilibili')}
            </a>
          </span>
          <span className="site-footer__link-group site-footer__link-group--external">
            <a href={PROJECT_LINKS.wiki} target="_blank" rel="noopener noreferrer">
              {t(locale, 'footer.dataSource')}
            </a>
            <a href={PROJECT_LINKS.balatro} target="_blank" rel="noopener noreferrer">
              {t(locale, 'footer.official')}
            </a>
          </span>
        </nav>
        <details className="site-footer__legal">
          <summary>{t(locale, 'footer.rightsPrivacy')}</summary>
          <div className="site-footer__legal-content">
            <p>{t(locale, 'footer.rightsNotice')}</p>
            <p>{t(locale, 'footer.nonCommercialNotice')}</p>
            <p>{t(locale, 'footer.codeLicenseNotice')}</p>
            <p>{t(locale, 'footer.privacyNotice')}</p>
            <p>
              {t(locale, 'footer.dataCredit')}{' '}
              <a href={PROJECT_LINKS.wiki} target="_blank" rel="noopener noreferrer">
                Balatro Wiki
              </a>
              {t(locale, 'footer.textLicenseOnly')}
            </p>
            <p>
              {t(locale, 'footer.rightsContact')}{' '}
              <a href={PROJECT_LINKS.x} target="_blank" rel="noopener noreferrer">
                @x6ncraft
              </a>
              {t(locale, 'footer.rightsResponse')}
            </p>
          </div>
        </details>
      </footer>

      <HelpDialog
        open={helpOpen}
        locale={locale}
        maxAttempts={state.maxAttempts}
        onClose={() => setHelpOpen(false)}
      />
      <StatsDialog
        open={statsOpen}
        locale={locale}
        stats={stats}
        onClose={() => setStatsOpen(false)}
      />
      {glossaryOpen ? (
        <ClueGlossaryDialog
          open
          locale={locale}
          jokers={jokers}
          onClose={() => setGlossaryOpen(false)}
        />
      ) : null}
      <JokerCollectionDialog
        open={collectionOpen}
        locale={locale}
        jokers={jokers}
        requiresConfirmation={requiresCollectionConfirmation}
        onClose={() => setCollectionOpen(false)}
        onConfirm={confirmCollection}
      />
    </main>
  )
}

// src/App.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, ref, watch } from 'vue'
import { BarChart3, BookOpen, CircleHelp, Languages, ListTree } from 'lucide-vue-next'

import ClueGlossaryDialog from './components/ClueGlossaryDialog.vue'
import GuessRow from './components/GuessRow.vue'
import HelpDialog from './components/HelpDialog.vue'
import JokerCombobox from './components/JokerCombobox.vue'
import JokerCollectionDialog from './components/JokerCollectionDialog.vue'
import ResultBanner from './components/ResultBanner.vue'
import StatsDialog from './components/StatsDialog.vue'
import { JOKER_DATA_META, jokers } from './data'
import type { Joker } from './data/types'
import {
  compareJokers,
  createDailyGame,
  createPracticeGame,
  formatShareResult,
  GAME_STORAGE_FALLBACK_CLASSIFICATION_VERSIONS,
  gameStorageKey,
  getBeijingDateKey,
  markCollectionUsed,
  restoreStoredGame,
  serializeGameState,
  submitGuess,
  type GameMode,
  type GameState,
  type GuessComparison,
} from './game'
import {
  LOCALE_STORAGE_KEY,
  resolveLocale,
  serializeLocalePreference,
  t,
  type Locale,
} from './i18n'
import {
  STATS_STORAGE_KEY,
  parseStats,
  recordCompletedDailyGame,
  type PlayerStats,
} from './state/stats'

const bootTime = new Date()
const today = getBeijingDateKey(bootTime)
const initialDailyGame = createDailyGame(jokers, bootTime)
const dailyAnswer = initialDailyGame.answerId
const dataKey = `${JOKER_DATA_META.gameVersion}:c${JOKER_DATA_META.classificationVersion}`
const dailyStorageKey = gameStorageKey(
  JOKER_DATA_META.gameVersion,
  JOKER_DATA_META.classificationVersion,
  'daily',
  today,
)
const practiceStorageKey = gameStorageKey(
  JOKER_DATA_META.gameVersion,
  JOKER_DATA_META.classificationVersion,
  'practice',
)
const previousClassificationVersions = GAME_STORAGE_FALLBACK_CLASSIFICATION_VERSIONS.filter(
  (version) => version < JOKER_DATA_META.classificationVersion,
)
const previousDailyStorageKeys = previousClassificationVersions.map((version) =>
  gameStorageKey(JOKER_DATA_META.gameVersion, version, 'daily', today),
)
const previousPracticeStorageKeys = previousClassificationVersions.map((version) =>
  gameStorageKey(JOKER_DATA_META.gameVersion, version, 'practice'),
)
const practiceBagKey = `balatrue:practice-bag:${dataKey}`
const validJokerIds = new Set(jokers.map((joker) => joker.id))
const jokersById = new Map(jokers.map((joker) => [joker.id, joker]))

function safeStorageGet(key: string): string | null {
  try {
    return localStorage.getItem(key)
  } catch {
    return null
  }
}

function safeStorageSet(key: string, value: string): boolean {
  try {
    localStorage.setItem(key, value)
    return true
  } catch {
    return false
  }
}

function refreshFallbackGame(storedState: GameState): GameState | null {
  const storedAnswer = jokersById.get(storedState.answerId)
  if (!storedAnswer) return null

  let refreshed: GameState = {
    ...storedState,
    status: 'playing',
    guesses: [],
  }
  try {
    for (const storedGuess of storedState.guesses) {
      const guessedJoker = jokersById.get(storedGuess.guessId)
      if (!guessedJoker) return null
      refreshed = submitGuess(refreshed, guessedJoker, storedAnswer)
    }
  } catch {
    return null
  }
  return refreshed.status === storedState.status ? refreshed : null
}

function restoredGame(
  key: string,
  fallbackKeys: readonly string[],
  mode: GameMode,
  answerId?: string,
): GameState | null {
  if (mode === 'daily' && !answerId) return null
  return restoreStoredGame({
    currentKey: key,
    fallbackKeys,
    context:
      mode === 'daily'
        ? { mode, puzzleKey: today, answerId: answerId as string }
        : { mode: 'practice' },
    validJokerIds,
    read: safeStorageGet,
    write: safeStorageSet,
    refreshFallback: refreshFallbackGame,
  })
}

function shuffledIds(): string[] {
  const result = jokers.map((joker) => joker.id)
  for (let index = result.length - 1; index > 0; index -= 1) {
    const random = new Uint32Array(1)
    crypto.getRandomValues(random)
    const swapIndex = (random[0] ?? 0) % (index + 1)
    const current = result[index]
    const swap = result[swapIndex]
    if (current && swap) {
      result[index] = swap
      result[swapIndex] = current
    }
  }
  return result
}

function nextPracticeGame(): GameState {
  let bag: string[] = []
  try {
    const stored: unknown = JSON.parse(localStorage.getItem(practiceBagKey) ?? '[]')
    if (Array.isArray(stored)) {
      bag = stored.filter(
        (id): id is string => typeof id === 'string' && jokers.some((joker) => joker.id === id),
      )
    }
  } catch {
    bag = []
  }
  if (bag.length === 0) bag = shuffledIds()

  const answerId = bag.shift()
  const sorted = [...jokers].sort((left, right) => left.number - right.number)
  const answerIndex = sorted.findIndex((joker) => joker.id === answerId)
  const randomValue = (Math.max(0, answerIndex) + 0.5) / sorted.length
  try {
    localStorage.setItem(practiceBagKey, JSON.stringify(bag))
  } catch {
    // A private browsing quota should not make practice mode unplayable.
  }

  return createPracticeGame(jokers, () => randomValue, {
    puzzleKey: `practice:${Date.now().toString(36)}`,
  })
}

const locale = ref<Locale>(
  resolveLocale({
    stored: safeStorageGet(LOCALE_STORAGE_KEY),
    preferredLanguages: navigator.languages,
  }),
)
const mode = ref<GameMode>('daily')
const dailyState = ref<GameState>(
  restoredGame(dailyStorageKey, previousDailyStorageKeys, 'daily', dailyAnswer) ?? initialDailyGame,
)
const practiceState = ref<GameState | null>(
  restoredGame(practiceStorageKey, previousPracticeStorageKeys, 'practice'),
)
const helpOpen = ref(false)
const statsOpen = ref(false)
const glossaryOpen = ref(false)
const collectionOpen = ref(false)
const notice = ref('')
const copied = ref(false)
const resetToken = ref(0)
const stats = ref<PlayerStats>(parseStats(safeStorageGet(STATS_STORAGE_KEY)))

const state = computed(() =>
  mode.value === 'daily' ? dailyState.value : (practiceState.value ?? nextPracticeGame()),
)
const answer = computed(() => {
  const found = jokers.find((joker) => joker.id === state.value.answerId)
  if (!found) throw new Error(`Missing answer ${state.value.answerId}`)
  return found
})
const guessedIds = computed(() => state.value.guesses.map((guess) => guess.guessId))
const guessRows = computed(() =>
  state.value.guesses.flatMap((comparison) => {
    const joker = jokers.find((candidate) => candidate.id === comparison.guessId)
    return joker ? [{ joker, comparison }] : []
  }),
)
const remainingAttempts = computed(() => state.value.maxAttempts - state.value.guesses.length)
const requiresCollectionConfirmation = computed(
  () => mode.value === 'daily' && state.value.status === 'playing' && !state.value.usedCollection,
)

function sameVisibleFeedback(left: GuessComparison, right: GuessComparison): boolean {
  return (
    left.rarity.result === right.rarity.result &&
    left.rarity.direction === right.rarity.direction &&
    left.acquisition.result === right.acquisition.result &&
    left.acquisition.direction === right.acquisition.direction &&
    left.effects.result === right.effects.result &&
    left.timings.result === right.timings.result &&
    left.dependencies.result === right.dependencies.result
  )
}

const possibleCount = computed(() => {
  if (state.value.guesses.length === 0) return jokers.length
  if (state.value.status === 'won') return 1
  const guessed = new Set(guessedIds.value)

  return jokers.filter((candidate) => {
    if (guessed.has(candidate.id)) return false
    return state.value.guesses.every((record) => {
      const guessedJoker = jokers.find((joker) => joker.id === record.guessId)
      return guessedJoker
        ? sameVisibleFeedback(compareJokers(guessedJoker, candidate), record)
        : false
    })
  }).length
})

const formattedDate = computed(() => {
  const [year, month, day] = today.split('-').map(Number)
  return new Intl.DateTimeFormat(locale.value === 'zh-CN' ? 'zh-CN' : 'en', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    timeZone: 'Asia/Shanghai',
  }).format(new Date(Date.UTC(year ?? 2026, (month ?? 1) - 1, day ?? 1, 12)))
})

function saveState(next: GameState): void {
  const key = next.mode === 'daily' ? dailyStorageKey : practiceStorageKey
  if (!safeStorageSet(key, serializeGameState(next))) {
    notice.value = t(locale.value, 'error.storageUnavailable')
  }
}

function finishDaily(next: GameState): void {
  if (next.mode !== 'daily' || next.status === 'playing') return
  stats.value = recordCompletedDailyGame(stats.value, next)
  if (!safeStorageSet(STATS_STORAGE_KEY, JSON.stringify(stats.value))) {
    notice.value = t(locale.value, 'error.storageUnavailable')
  }
}

async function revealLatestFeedback(next: GameState): Promise<void> {
  await nextTick()
  const target = document.querySelector<HTMLElement>(
    next.status === 'playing' ? '.guess-row:last-child' : '.result-banner',
  )
  if (!target) return
  const bounds = target.getBoundingClientRect()
  if (bounds.top >= 0 && bounds.bottom <= window.innerHeight) return

  const isNarrowScreen = window.matchMedia('(max-width: 760px)').matches
  target.scrollIntoView({
    block: isNarrowScreen ? 'center' : 'nearest',
    behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth',
  })
}

function submit(joker: Joker): void {
  notice.value = ''
  try {
    const next = submitGuess(state.value, joker, answer.value)
    if (mode.value === 'daily') dailyState.value = next
    else practiceState.value = next
    saveState(next)
    finishDaily(next)
    resetToken.value += 1
    void revealLatestFeedback(next)
  } catch (error) {
    notice.value =
      error instanceof Error && error.message.includes('already')
        ? t(locale.value, 'error.duplicateGuess')
        : t(locale.value, 'error.invalidGuess')
  }
}

function setMode(next: GameMode): void {
  if (mode.value === next) return
  mode.value = next
  notice.value = ''
  copied.value = false
  resetToken.value += 1
  if (next === 'practice' && !practiceState.value) {
    practiceState.value = nextPracticeGame()
    saveState(practiceState.value)
  }
}

function startNext(): void {
  if (mode.value === 'daily') {
    mode.value = 'practice'
  }
  practiceState.value = nextPracticeGame()
  saveState(practiceState.value)
  notice.value = ''
  copied.value = false
  resetToken.value += 1
}

function confirmCollection(): void {
  if (mode.value !== 'daily') return
  const next = markCollectionUsed(dailyState.value)
  if (next === dailyState.value) return
  dailyState.value = next
  saveState(next)
  notice.value = t(locale.value, 'collection.assistedNotice')
}

async function copyResult(): Promise<void> {
  const result = formatShareResult(state.value, {
    title: 'Balatrue',
    url: window.location.origin,
  })
  let didCopy = false
  try {
    await navigator.clipboard.writeText(result)
    didCopy = true
  } catch {
    const textarea = document.createElement('textarea')
    textarea.value = result
    textarea.style.position = 'fixed'
    textarea.style.opacity = '0'
    document.body.append(textarea)
    textarea.select()
    didCopy = document.execCommand('copy')
    textarea.remove()
  }
  if (!didCopy) {
    notice.value = t(locale.value, 'error.generic')
    return
  }
  copied.value = true
  window.setTimeout(() => (copied.value = false), 1800)
}

function toggleLocale(): void {
  locale.value = locale.value === 'zh-CN' ? 'en' : 'zh-CN'
}

watch(locale, (next) => {
  safeStorageSet(LOCALE_STORAGE_KEY, serializeLocalePreference(next))
  document.documentElement.lang = next
  document.title = next === 'zh-CN' ? 'Balatrue · 猜丑牌' : 'Balatrue · Daily Joker Puzzle'
})

onMounted(() => {
  document.documentElement.lang = locale.value
  finishDaily(dailyState.value)
})
</script>

<template>
  <main class="app-shell">
    <header class="topbar">
      <div class="brand" aria-label="Balatrue 猜丑牌">
        <p class="brand__name">BALA<span>TRUE</span></p>
        <p class="brand__zh">猜丑牌</p>
      </div>
      <nav class="top-actions" :aria-label="locale === 'zh-CN' ? '页面工具' : 'Page tools'">
        <button
          class="collection-button"
          type="button"
          :aria-label="t(locale, 'a11y.openCollection')"
          @click="collectionOpen = true"
        >
          <BookOpen :size="18" aria-hidden="true" />
          <span>{{ t(locale, 'nav.collection') }}</span>
        </button>
        <button
          class="icon-button"
          type="button"
          :aria-label="t(locale, 'stats.title')"
          @click="statsOpen = true"
        >
          <BarChart3 :size="19" aria-hidden="true" />
        </button>
        <button
          class="icon-button"
          type="button"
          :aria-label="t(locale, 'a11y.openHelp')"
          @click="helpOpen = true"
        >
          <CircleHelp :size="19" aria-hidden="true" />
        </button>
        <button
          class="language-button"
          type="button"
          :aria-label="t(locale, 'a11y.openLanguageMenu')"
          @click="toggleLocale"
        >
          <Languages :size="18" aria-hidden="true" />
          <span>{{ locale === 'zh-CN' ? 'EN' : '中文' }}</span>
        </button>
      </nav>
    </header>

    <section class="game-card" aria-labelledby="puzzle-title">
      <header class="game-card__head">
        <div class="game-heading-row">
          <div class="mode-switch" :aria-label="locale === 'zh-CN' ? '游戏模式' : 'Game mode'">
            <button type="button" :aria-pressed="mode === 'daily'" @click="setMode('daily')">
              {{ t(locale, 'nav.daily') }}
            </button>
            <button type="button" :aria-pressed="mode === 'practice'" @click="setMode('practice')">
              {{ t(locale, 'nav.endless') }}
            </button>
          </div>
          <div>
            <p class="puzzle-kicker">
              {{ mode === 'daily' ? t(locale, 'game.today', { date: formattedDate }) : 'PRACTICE' }}
            </p>
            <h1 id="puzzle-title" class="puzzle-title">
              {{ mode === 'daily' ? t(locale, 'brand.tagline') : t(locale, 'game.endlessTitle') }}
            </h1>
            <p class="puzzle-rule">
              {{ t(locale, 'game.instructions') }}
              {{ t(locale, 'feedback.legend') }}
            </p>
          </div>
        </div>

        <JokerCombobox
          :jokers="jokers"
          :locale="locale"
          :guessed-ids="guessedIds"
          :disabled="state.status !== 'playing'"
          :reset-token="resetToken"
          @submit="submit"
          @invalid="notice = t(locale, 'error.invalidGuess')"
        />

        <div class="game-meta">
          <ul class="legend" :aria-label="locale === 'zh-CN' ? '反馈图例' : 'Feedback legend'">
            <li>
              <span class="legend-dot legend-dot--exact">✓</span>{{ t(locale, 'feedback.exact') }}
            </li>
            <li>
              <span class="legend-dot legend-dot--partial">◐</span
              >{{ t(locale, 'feedback.partial') }}
            </li>
            <li>
              <span class="legend-dot legend-dot--miss">×</span>{{ t(locale, 'feedback.miss') }}
            </li>
          </ul>
          <div class="game-meta__right">
            <button class="glossary-link" type="button" @click="glossaryOpen = true">
              <ListTree :size="15" aria-hidden="true" />
              {{ t(locale, 'action.openGlossary') }}
            </button>
            <span v-if="state.mode === 'daily' && state.usedCollection" class="assisted-badge">
              <BookOpen :size="14" aria-hidden="true" />
              {{ t(locale, 'game.assisted') }}
            </span>
            <span class="game-meta__count">
              {{ t(locale, 'game.remaining', { count: remainingAttempts }) }} ·
              {{
                locale === 'zh-CN'
                  ? `约 ${possibleCount} 张仍符合线索`
                  : `About ${possibleCount} still fit`
              }}
            </span>
          </div>
        </div>
        <div v-if="notice" class="notice" role="status">{{ notice }}</div>
      </header>

      <div class="guess-area">
        <ResultBanner
          v-if="state.status !== 'playing'"
          :state="state"
          :answer="answer"
          :locale="locale"
          :copied="copied"
          @share="copyResult"
          @next="startNext"
        />

        <div v-if="guessRows.length === 0" class="empty-board">
          <div>
            <span class="empty-board__mark" aria-hidden="true">?</span>
            <p>
              {{ t(locale, 'state.empty') }}{{ locale === 'zh-CN' ? '。' : '. '
              }}{{ t(locale, 'search.hint') }}
            </p>
          </div>
        </div>
        <section v-else class="guess-table" :aria-label="t(locale, 'a11y.guessHistory')">
          <div class="guess-header" aria-hidden="true">
            <span>{{ t(locale, 'clue.joker') }}</span>
            <span>{{ t(locale, 'clue.rarity') }}</span>
            <span>{{ t(locale, 'clue.price') }}</span>
            <span>{{ t(locale, 'clue.effect') }}</span>
            <span>{{ t(locale, 'clue.timing') }}</span>
            <span>{{ t(locale, 'clue.dependency') }}</span>
          </div>
          <GuessRow
            v-for="row in guessRows"
            :key="row.joker.id"
            :joker="row.joker"
            :comparison="row.comparison"
            :locale="locale"
          />
        </section>
      </div>
    </section>

    <footer class="site-footer">
      <span>{{ t(locale, 'brand.disclaimer') }}</span>
      <span>
        {{ JOKER_DATA_META.gameVersion }} · 150 Jokers ·
        {{ locale === 'zh-CN' ? '进度仅保存在本机' : 'Progress stays on this device' }}
      </span>
    </footer>

    <HelpDialog :open="helpOpen" :locale="locale" @close="helpOpen = false" />
    <StatsDialog :open="statsOpen" :locale="locale" :stats="stats" @close="statsOpen = false" />
    <ClueGlossaryDialog
      :open="glossaryOpen"
      :locale="locale"
      :jokers="jokers"
      @close="glossaryOpen = false"
    />
    <JokerCollectionDialog
      :open="collectionOpen"
      :locale="locale"
      :jokers="jokers"
      :requires-confirmation="requiresCollectionConfirmation"
      @close="collectionOpen = false"
      @confirm="confirmCollection"
    />
  </main>
</template>
